server:
  port: 8082

spring:
  application:
    name: portfolio-service

  config:
    import: "optional:configserver:http://localhost:8888"

  datasource:
    url: jdbc:mysql://localhost:3306/portfolio_db
    username: root
    password: Rahul2140@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
    com:
      dbs:
        portfolio_service: DEBUG

file:
  name: portfolio-service.log